Add toPromise to await a value that matches certain conditions
mobxjs/mobx-utils pull request #285
Opened 2020-12-11 00:41 UTC by reuzel

Hereby a proposal for an addition that allows the creation of a promise that resolves when a certain observed value become available and matches an (optionally) provided predicate. This allows the creation of a promise that resolves when a certain value is added to a map, when a certain value matches some condition, etc. The difference with mobx-when is that the promise resolves with the actual observed value.

Regards,
Joost

2021-03-13 14:57 UTC, NaridaL requested changes
You need to update the readme by running `yarn build-docs`.

2021-03-13 14:57 UTC, NaridaL commented on src/whenValue.ts
> +    let cancel: () => void = () => undefined
You can do `let cancel!: () => void` to avoid assigning a value which will never be used.

2021-03-13 14:57 UTC, NaridaL commented on src/whenValue.ts
> +                reaction.dispose()
reject can't throw, right?

2021-03-13 14:57 UTC, NaridaL commented on src/whenValue.ts
> + *  *
Can we format the example code like the actual code?

2021-03-13 14:57 UTC, NaridaL commented on src/whenValue.ts
> +    return res
You can do `Object.assign(new Promise(...), { cancel })` to avoid casting.

2021-08-16 20:14 UTC, mweststrate commented
Closing for inactivity.

2021-08-16 20:14 UTC, closed without merging